# k8s/apps/fastapi-gateway/values.yaml
image:
  repository: 700274427720.dkr.ecr.us-east-1.amazonaws.com/fastapi-model
  tag: "latest"                # default; ArgoCD/CI can override via helm parameters
  pullPolicy: IfNotPresent

service:
  port: 8080

ingress:
  enabled: true
  className: alb
  # If you don't have a DNS host, you can omit `host` entirely and ALB will still work on its DNS name.
  hosts:
    - # host: your-api.example.com   # (optional) set when you own a domain
      paths:
        - path: /
          pathType: Prefix
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'

modelService:
  url: "http://vllm:8000"

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

extraEnv:
  - name: MODEL_NAME
    value: "meta-llama/Llama-3-8b-instruct"
