# k8s/apps/fastapi-gateway/values.yaml
image:
  repository: 700274427720.dkr.ecr.us-east-1.amazonaws.com/fastapi-model
  tag: "fa968e5bbdee254bf728ef5992b8ad579e543be6"
  pullPolicy: IfNotPresent

service:
  port: 8080

ingress:
  enabled: true
  className: alb
  hosts:
    # - host: your-api.example.com   # or omit; ALB DNS will work without a host
      paths:
        - path: /
          pathType: Prefix
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'

modelService:
  url: "http://vllm:8000"

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

extraEnv:
  - name: MODEL_NAME
    value: "meta-llama/Llama-3-8b-instruct"
