apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  # Create a service account named 'ci' that can mint API keys
  accounts.ci: apiKey
  # Optional hardening: disable the built-in admin once you’re ready
  # admin.enabled: "false"
