apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-cache
  namespace: inference
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  storageClassName: {{ .Values.storage.storageClassName | default "" | quote }}
