apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-user/your-repo.git
    targetRevision: main
    path: k8s/apps/fastapi-gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: inference
  syncPolicy:
    automated: { prune: true, selfHeal: true }
