apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/CSpiegelhalter/deploy-llm-eks.git
    targetRevision: main
    path: k8s/apps/fastapi-gateway   # <--- folder that contains Chart.yaml
    helm:
      valueFiles: [values.yaml]
  destination:
    server: https://kubernetes.default.svc
    namespace: fastapi                 # <--- app namespace (will be created)
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true
